<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>MML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(;|//)</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.mml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.mml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^#(GAME|TITLE|COMPOSER|PROGRAMMER|MAKER|OCTAVE-REV|EX-DISKFM|EX-NAMCO106|EX-VRC6|EX-VRC7|EX-MMC5|EX-FME7|BANK-CHANGE|EFFECT-INCLUDE|NO-BANKSWITCH|SETBANK|DPCM-RESTSTOP)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.mml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]+"</string>
			<key>name</key>
			<string>string.mml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[-.+0-9]+\b</string>
			<key>name</key>
			<string>constant.mml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@*(OP0|EPOF|ENOF|MHOF|MPOF|(vr?|q|EP|EN|MP|DPCM|FM||N|MW|MH|D-?)[0-9]+)\b</string>
			<key>name</key>
			<string>variable.macro.mml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z]+\b</string>
			<key>name</key>
			<string>constant.mml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.mml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.mml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-z][-+]*)([0-9]*\.*\^*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[=&gt;&lt;\^]</string>
			<key>name</key>
			<string>keyword.mml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>song.mml</string>
	<key>uuid</key>
	<string>C914C3E8-3E0E-405E-97FB-0081B2F56430</string>
</dict>
</plist>
